source 'https://github.com/CocoaPods/Specs.git'

target 'NNUIThreadBlockObserver_Example', :exclusive => true do
  pod "NNUIThreadBlockObserver", :path => "../"
end

target 'NNUIThreadBlockObserver_Tests', :exclusive => true do
  pod "NNUIThreadBlockObserver", :path => "../"

  
end
